export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_FETCH = "GET_QUESTION_FETCH";
export const GET_QUESTION_USERS = "GET_QUESTION_USERS";
const const ADD_QUESTIONS = 'ADD_QUESTIONS'
